### ISSUE TITLE
Should `grow_memory` have a return value?

### ISSUE THREAD

**Issue by JSStats** [WebAssembly/design#525] opened 2016-01-24 01:06 UTC
The v8 encoding defines `grow_memory` to return an i32, but the ml-proto defines it to return no values. Can it be defined to return the new linear memory size.

**Comment by sunfishcode** [comment] 2016-02-18 19:45
We have a `memory_size` operator for when programs need to know the size. `grow_memory` isn't suitable for find-grained allocation, so it doesn't need the low-level optimization of saving the user a use of `memory_size`. It's simpler with no return value.

**Comment by jfbastien** [comment] 2016-02-18 22:20
Returning a value would allow the same clever-ism as `store` returning a value. Not as useful, but it could be a theme in the AST design.

**Comment by JSStats** [comment] 2016-02-19 03:55
I echo the concern that `memory_size` is not 'suitable for find-grained allocation', and the suggestion that it have 'no return value' for now. Having it return a value in future would likely not invalidate code written now that expects no value (with some unresolved cases), so might be the better short term solution until there is consensus on a future use. 

Practically code making fine-grain allocations in performance critical code could allocate from a pointer stored in memory (thread local variable in future) in which case `grow_memory` is cold code.

**Comment by titzer** [comment] 2016-02-19 10:52
I agree with Dan; it's a side-effecting operation, and we shouldn't make it
do dual-duty as a query operation.

We could have it return success/failure, but I would prefer that it not
return the current or last memory size.

**Comment by JSStats** [comment] 2016-02-19 12:11
Could ponder if there are any obvious advantages one way or the other for thread safety. Might there be some advantage to an atomic grow-query operation. What about synchronization between `grow_memory` and `memory_size`. Would `memory_size` be a heavy operation too locking against `grow_memory`. At least returning a success/fail flag might help thread safety for some code, so that there is an atomic grow/result operation that does not need locking. Locking in low level code can a deadlock hazard, and perhaps an allocator could avoid it. If there is a parallel to kernel operations then returning an atomic success/fail flag would help with thread safety (errno was problematic, moved to thread local state). But success might not be true/false here, it might get only some of the requested memory, so perhaps returning the amount is a good result value.

**Comment by JSStats** [comment] 2016-02-19 13:52
Multiple return values can also good for thread safety as they allow a set of values to be returned atomically. This could allow return of an error number (including success) plus a memory value, without having to encode the error number in the result value.

I see work on musl, but perhaps the calls to the embedder need to be specified, and rather than calls such as 'open' returning an fd on success and an error code in a separate location, it would be clean to use mv support to return both, and this is good for thread safety, and interrupt safety if that is ever supported (signals). Musl could then put the error number in thread local storage for the errno, and other languages with mv support might accept the errno as just one of the values. If `grow_memory` is to follow a systematic pattern for system calls then it might want to use the same strategy. If MVP needs these system calls defined then it might also want mv support.

**Comment by sunfishcode** [comment] 2016-02-19 16:23
@JSStats The interaction with threads is a good point.

If two threads call `grow_memory`, the VM should correctly allocate the sum of the requested memory. However, without a return value, the threads have no way to know which region of newly allocated memory is "theirs". Consequently, I now think it makes sense to have `grow_memory` return the old memory size.

**Comment by jfbastien** [comment] 2016-02-19 16:26
Interesting. Something like a cmpxchg? Realistically the mmap runtime will be serialized so I'm not sure this is a huge issue, but I like the cleverness that can come out of it.

Do we want similar clever-isms elsewhere?

**Comment by lukewagner** [comment] 2016-02-19 16:26
Agreed.  So on successful return, your thread would know it got the range [`old_size`, `old_size + request_size`), where `old_size + request_size <= memory_size`.

Also an error return value (probably `-1`, since `0` is a valid initial memory size) seems appropriate for apps that want to gracefully handle OOM (I'm thinking of large memory requests).

**Comment by lukewagner** [comment] 2016-02-19 16:28
@jfbastien The issue is that, without some external coordination, your thread wouldn't be able to assume that it had gotten the range [`memory_size - request_size`, `memory_size`).

**Comment by jfbastien** [comment] 2016-02-19 16:31
@lukewagner agreed, what I'm saying is that a user-space memory manager does synchronize, and tracks which memory it gave out. When it sbrks it does so while holding a lock, and when it hands out the memory it also synchronizes.

Of course, a different approach can be taken, and this clever bit enables it.

**Comment by lukewagner** [comment] 2016-02-19 16:32
It'd be nice if we didn't force all applications to critically rely on that external coordination for such a simple task where we have exactly the info that is necessary.

**Comment by titzer** [comment] 2016-02-19 16:34
The multi-threaded case is compelling, so I support his now as well.

**Comment by sunfishcode** [comment] 2016-02-22 17:01
#544 adds a return value to `grow_memory` and is now merged.

**Closed by sunfishcode** 2016-02-22 17:01 UTC
