### ISSUE TITLE
Does someone here know which approche is the best ? calling c++ fuction with bind from javascript module or just fetch wasm file ? i'm just curious =)

### ISSUE THREAD

**Issue by extremety1989** [WebAssembly/design#1110] opened 2017-07-21 08:14 UTC

**Comment by RyanLamansky** [comment] 2017-07-21 12:39
This seems like a duplicate of #1106...

**Comment by jfbastien** [comment] 2017-07-21 18:44
Please don't open multiple issues for the same question.

**Closed by jfbastien** 2017-07-21 18:44 UTC
