### ISSUE TITLE
bswap instruction

### ISSUE THREAD

**Issue by Maratyszcza** [WebAssembly/design#725] opened 2016-07-14 18:14 UTC
The `bswap` instruction reverses the byte order in a word. This instruction is natively implemented on  x86/x86-64 (as `bswap` since Pentium), ARM (as `rev` since ARMv6) and MIPS (as `wsbh` since MIPS32 R2). The natural use-case for this instruction is conversion of byte order for serialization with big-endian formats, and it may seem rare enough to ignore. However, there is another, less trivial area where this instruction is crucial: reading and writing bit streams. Bits inside a byte are conventionally numbered from right to left, but in big-endian format bytes inside a word a numbered left-to-right. Therefore, either bit swap within a byte or byte swap within a word is required when working with bit streams. Higher-level applications of bitstream writers and readers include Huffman coding, variable-length universal codes (unary coding, Rice codes, Exp-Golomb), arithmetic coding, and eventually nearly all compression algorithms. As Web Assembly applications will run inside Web browsers, it is important that compression algorithms can be efficiently implemented with this format, and `bswap` instruction is crucial for high-performance implementations.

I know that `i32.bswap` instruction is listed in FutureFeatures, but I strongly suggest to consider its inclusion in the current WAsm spec.

**Comment by jfbastien** [comment] 2016-07-14 18:51
Dupe of #422.

**Closed by jfbastien** 2016-07-14 18:51 UTC

**Comment by Maratyszcza** [comment] 2016-07-14 18:57
#422 concludes with `Byteswaps can be addressed separately, if desired.`
